apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: acmeair-mongo
  name: acmeair-mongo
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: acmeair-mongo
    spec:
      volumes:
        - name: mongo-pv-storage
          persistentVolumeClaim:
            claimName: mongo-pv-claim
      containers:
      - image: mongo
        name: acmeair-mongo
        ports:
        - containerPort: 27017
        resources: {}
        volumeMounts:
          - mountPath: "/data/db"
            name: mongo-pv-storage
      restartPolicy: Always
status: {}
