# Copyright 2017 Huawei Technologies Co., Ltd
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: acmeair-customerservice
  name: acmeair-customerservice
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: acmeair-customerservice
    spec:
      containers:
      - env:
        - name: JAR_NAME
          value: acmeair-customer-service
        - name: JAVA_OPTS
          value: -Dspring.profiles.active=mongodb -Dserver.port=8080 -Dspring.data.mongodb.host=acmeair-mongo -Dcse.service.registry.address=http://service-center:30100
        image: zenlintechnofreak/acmeair-customer-service:2.0.0-SNAPSHOT
        name: acmeair-customerservice
        ports:
        - containerPort: 8082
        resources:
          requests:
            cpu: 200m
      restartPolicy: Always
status: {}
