apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: acmeair-webapp
  name: acmeair-webapp
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
    nodePort: 30101
    protocol: "TCP"
  type: NodePort
  selector:
    io.kompose.service: acmeair-webapp
status:
  loadBalancer: {}
