apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: acmeair-customerservice
  name: acmeair-customerservice
spec:
  ports:
  - name: "8084"
    port: 8084
    targetPort: 8082
  selector:
    io.kompose.service: acmeair-customerservice
status:
  loadBalancer: {}
